In [1]:
from __future__ import print_function
import torch

In [14]:
# Initialising a tensor like this keeps populating it with zeros and random values 
# (not sure why yet. Also it has both positive and negative zeros)
x = torch.Tensor(5, 3)
print(x)


    -0.0000      0.0000     -0.0000
     0.0000      0.0000      0.0000
 53495.1875      0.0000      0.0000
     0.0000      0.0000      0.0000
     0.0000      0.0000      0.0000
[torch.FloatTensor of size 5x3]



In [21]:
# This way they are all random
x = torch.rand(5, 3)
print(x)


 0.5731  0.7295  0.8459
 0.5970  0.1136  0.2107
 0.4612  0.7283  0.0813
 0.9585  0.6535  0.3484
 0.4131  0.0427  0.1175
[torch.FloatTensor of size 5x3]



In [32]:
print(x.size())

torch.Size([5, 3])


In [33]:
y = torch.rand(5, 3)
print(x + y)


 1.3519  1.3140  0.9386
 0.9670  0.8756  0.2961
 1.1770  1.5033  0.4334
 1.1743  1.4321  0.8405
 1.0954  0.9291  0.7459
[torch.FloatTensor of size 5x3]



In [34]:
print(torch.add(x, y))


 1.3519  1.3140  0.9386
 0.9670  0.8756  0.2961
 1.1770  1.5033  0.4334
 1.1743  1.4321  0.8405
 1.0954  0.9291  0.7459
[torch.FloatTensor of size 5x3]



In [43]:
# Has to be torch tensors
p = [[1, 1, 1],[2, 2, 2],[3, 3, 3]]
q = [[1, 1, 1],[2, 2, 2],[3, 3, 3]]
print(torch.add(p+q))

TypeError: torch.add received an invalid combination of arguments - got (list), but expected one of:
 * (torch.FloatTensor source, float value)
 * (torch.FloatTensor source, torch.FloatTensor other)
 * (torch.FloatTensor source, torch.SparseFloatTensor other)
 * (torch.FloatTensor source, float value, torch.FloatTensor other)
 * (torch.FloatTensor source, float value, torch.SparseFloatTensor other)


In [46]:
result = torch.Tensor(5, 3) # create tensor of same size as output
torch.add(x, y, out=result)
print(result)


 1.9250  2.0435  1.7845
 1.5640  0.9892  0.5068
 1.6382  2.2316  0.5147
 2.1327  2.0855  1.1889
 1.5085  0.9718  0.8634
[torch.FloatTensor of size 5x3]



In [47]:
# adds x to y
y.add_(x)
print(y)


 1.9250  2.0435  1.7845
 1.5640  0.9892  0.5068
 1.6382  2.2316  0.5147
 2.1327  2.0855  1.1889
 1.5085  0.9718  0.8634
[torch.FloatTensor of size 5x3]



In [49]:
# Normal indexing through arrays
print(x[:, 0])


 0.5731
 0.5970
 0.4612
 0.9585
 0.4131
[torch.FloatTensor of size 5]



In [50]:
a = torch.ones(5)
print(a)

# Convert to numpy
b = a.numpy()
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [51]:
a.add_(1)
print(a)
print(b) # b is still linked to a


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [52]:
# going from numpy to torch
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [55]:
# Run with cuda easily
if torch.cuda.is_available():
    print('using CUDA')
    x = x.cuda()
    y = y.cuda()
    x + y

using CUDA
